module.exports = {
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]s$': ['ts-jest', { diagnostics: { warnOnly: true } }],
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@abroad-matrimony/shared$': '<rootDir>/../../libs/shared/src/index.ts',
    '^@abroad-matrimony/config$': '<rootDir>/../../libs/config/src/index.ts',
    '^@abroad-matrimony/logger$': '<rootDir>/../../libs/logger/src/index.ts',
    '^@abroad-matrimony/cache$': '<rootDir>/../../libs/cache/src/index.ts',
    '^@abroad-matrimony/db$': '<rootDir>/../../libs/db/src/index.ts',
    '^@abroad-matrimony/event-bus$': '<rootDir>/../../libs/event-bus/src/index.ts',
    '^@abroad-matrimony/queue$': '<rootDir>/../../libs/queue/src/index.ts',
    '^@abroad-matrimony/auth$': '<rootDir>/../../libs/auth/src/index.ts',
    '^@abroad-matrimony/profile$': '<rootDir>/../../libs/profile/src/index.ts',
    '^@abroad-matrimony/storage$':   '<rootDir>/../../libs/storage/src/index.ts',
    '^@abroad-matrimony/matching$':     '<rootDir>/../../libs/matching/src/index.ts',
    '^@abroad-matrimony/connections$':  '<rootDir>/../../libs/connections/src/index.ts',
    '^@abroad-matrimony/groups$':       '<rootDir>/../../libs/groups/src/index.ts',
    '^@abroad-matrimony/firebase$':      '<rootDir>/../../libs/firebase/src/index.ts',
    '^@abroad-matrimony/messaging$':    '<rootDir>/../../libs/messaging/src/index.ts',
    '^@abroad-matrimony/notification$': '<rootDir>/../../libs/notification/src/index.ts',
    '^@abroad-matrimony/payment$':          '<rootDir>/../../libs/payment/src/index.ts',
    '^@abroad-matrimony/verification$':     '<rootDir>/../../libs/verification/src/index.ts',
    '^@abroad-matrimony/habits$':           '<rootDir>/../../libs/habits/src/index.ts',
    '^@abroad-matrimony/introductions$':    '<rootDir>/../../libs/introductions/src/index.ts',
    '^@abroad-matrimony/gatherings$':       '<rootDir>/../../libs/gatherings/src/index.ts',
    '^@abroad-matrimony/prompts$':          '<rootDir>/../../libs/prompts/src/index.ts',
    '^@abroad-matrimony/saved-profiles$':   '<rootDir>/../../libs/saved-profiles/src/index.ts',
    '^@abroad-matrimony/trust$':            '<rootDir>/../../libs/trust/src/index.ts',
    '^@abroad-matrimony/ai$':               '<rootDir>/../../libs/ai/src/index.ts',
  },
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
};
