import { z } from 'zod';
import { MessageType } from '@abroad-matrimony/messaging';

// ─── Allowed MIME types for media uploads ─────────────────────────────────────

export const ALLOWED_IMAGE_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'] as const;
export const ALLOWED_VOICE_MIME_TYPES = ['audio/m4a', 'audio/webm'] as const;
export const ALLOWED_MIME_TYPES = [
  ...ALLOWED_IMAGE_MIME_TYPES,
  ...ALLOWED_VOICE_MIME_TYPES,
] as const;

// ─── POST /conversations/:convId/messages ─────────────────────────────────────

/**
 * Body schema for sending a message.
 *
 * Rules:
 *   - `type` must be TEXT, IMAGE, or VOICE (not SYSTEM — system messages are
 *     generated by the backend only)
 *   - `content` must be a non-empty string
 *     - For TEXT: the message body
 *     - For IMAGE / VOICE: the public S3/CloudFront URL obtained from upload-url
 *   - `durationSeconds` is optional but recommended for VOICE messages
 */
export const sendMessageBodySchema = z.object({
  type: z
    .nativeEnum(MessageType)
    .refine((t) => t !== MessageType.SYSTEM, {
      message: 'SYSTEM messages cannot be sent by users.',
    }),
  content: z.string().trim().min(1, 'content must not be empty'),
  durationSeconds: z.number().int().positive().optional(),
});

export type SendMessageBody = z.infer<typeof sendMessageBodySchema>;

// ─── GET /conversations/:convId/upload-url ────────────────────────────────────

/**
 * Query schema for the presigned upload URL endpoint.
 *
 * `type` + `mimeType` must be compatible:
 *   - type=image → mimeType must be image/jpeg, image/png, or image/webp
 *   - type=voice → mimeType must be audio/m4a or audio/webm
 */
export const uploadUrlQuerySchema = z
  .object({
    type:     z.enum(['image', 'voice']),
    mimeType: z.enum(ALLOWED_MIME_TYPES),
  })
  .superRefine(({ type, mimeType }, ctx) => {
    if (type === 'image' && !(ALLOWED_IMAGE_MIME_TYPES as readonly string[]).includes(mimeType)) {
      ctx.addIssue({
        code:    z.ZodIssueCode.custom,
        path:    ['mimeType'],
        message: `For type=image, mimeType must be one of: ${ALLOWED_IMAGE_MIME_TYPES.join(', ')}`,
      });
    }
    if (type === 'voice' && !(ALLOWED_VOICE_MIME_TYPES as readonly string[]).includes(mimeType)) {
      ctx.addIssue({
        code:    z.ZodIssueCode.custom,
        path:    ['mimeType'],
        message: `For type=voice, mimeType must be one of: ${ALLOWED_VOICE_MIME_TYPES.join(', ')}`,
      });
    }
  });

export type UploadUrlQuery = z.infer<typeof uploadUrlQuerySchema>;
